### ISSUE TITLE
[3주차] 업무에 바로 쓰는 SQL 튜닝_3장_이민선

### ISSUE THREAD

**Issue by alstjs37** [AEGIS-TECH/aegis#11]
# Q. 그래서 튜닝을 어떤 경우에 사용하는건데 ?

## Answer

https://zambbon.tistory.com/entry/MySQLMariaDB-%EC%97%85%EB%AC%B4%EC%97%90-%EB%B0%94%EB%A1%9C-%EC%93%B0%EB%8A%94-SQL-%ED%8A%9C%EB%8B%9D-%EC%B1%85-%ED%9B%84%EA%B8%B0

---

#### Before
```sql
SELECT 매핑.사원번호,
       부서.부서번호
FROM 부서사원_매핑 매핑,
     부서
WHERE 매핑.부서번호 = 부서.부서번호
  AND 매핑.시작일자 >= '2002-03-01';
```

#### After
```sql
SELECT STRAIGHT JOIN 
       매핑.사원번호,
       부서.부서번호
FROM 부서사원_매핑 매핑,
     부서
WHERE 매핑.부서번호 = 부서.부서번호
  AND 매핑.시작일자 >= '2002-03-01';
```

<br>

- 부서사원_매핑 (Rows - 331143)
<img width="144" alt="스크린샷 2024-10-14 오후 6 01 45" src="https://github.com/user-attachments/assets/678a6a6b-a896-4596-8928-e91347721536">

---

-  부서 (Rows - 9)
<img width="120" alt="스크린샷 2024-10-14 오후 6 01 27" src="https://github.com/user-attachments/assets/692f1361-c678-4b87-a130-aa38d087ee06">

---

#### 결론
- 작은 테이블을 드라이빙 테이블로 잡고 드리븐 테이블로 큰 테이블을 잡으면 당연히 IO가 많아질 수밖에 없음
- 두 SQL문은 `STRAIGHT JOIN ` 한줄 차이
- 한 줄차이지만 시간을 확실히 줄이는 방법이 될 수있기 때문에 튜닝은 중요하다

<img width="186" alt="스크린샷 2024-10-14 오후 6 11 56" src="https://github.com/user-attachments/assets/a041d393-05e0-4bd5-88e9-b9713cf847d6">

- 0.10299800 vs 0.00309700
- The value 0.00309700 is approximately 33.26 times smaller than 0.10299800.

**Comment by ehdwoKIM** [comment]
좋은 이슈 공유 감사합니다 ㅎㅎ
